- type: job
  id: PreventorEnforcer
  setPreference: true
  name: "превентивний примус"
  description: "переконайтеся, що комерційні угоди між урядом Ванкувера та \"Блакитною лінією\" виконані." #need work
  playTimeTracker: PreventorEnforcer
  startingGear: PreventorEnforcerGear
  icon: "JobIconSecurityCadet"

- type: startingGear
  id: PreventorEnforcerGear
  equipment:
    head: N14ClothingHeadHatVancouver
    back: N14ClothingBackpackMilitaryFilled
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryPreventorFilled
    jumpsuit: N14ClothingUniformJumpsuitVancouver
    shoes: N14ClothingBootsCombat
    gloves: N14ClothingHandsGlovesCombat
    outerClothing: N14ClothingOuterVestLeather
    pocket1: N14WeaponPistol9mm
    pocket2: N14CombatKnife
    suitstorage: N14WeaponRifle556EM2

- type: playTimeTracker
  id: PreventorEnforcer
