- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunVector
  name: "векторний безпечний"
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunVector
      amount: 2
    - id: MagazineMagnumSubMachineGun
      amount: 4
