- type: entity
  id: CrateServiceReplacementColoredLights
  name: "Ящик з кольоровими ліхтарями"
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxColoredLighttube
        amount: 2

- type: entity
  id: CrateServiceReplacementMaintenanceLights
  name: "Ящик для технічних світильників"
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxMaintenanceLightbulb
        amount: 2
