- type: entity
  categories: [ HideSpawnMenu ]
  parent: BaseBullet
  id: N14Bullet50HEIAPMeta # for spawn turrets and fun
  name: "куля (протипіхотна куля .50 HEIAP)"
  components:
  - type: IgniteOnCollide
    fireStacks: 1
  - type: Projectile
    damage:
      types:
        Piercing: 500
        Blunt: 500
    ignoreResistances: true