- type: job
  id: ChineseGunner
  setPreference: true
  name: "китайський кулеметник"
  description: "виконуйте накази свого командира, боріться за комунізм з додатковою вогневою потужністю." #need work
  playTimeTracker: ChineseGunner
  startingGear: ChineseGunnerGear
  icon: "JobIconSecurityCadet"

- type: startingGear
  id: ChineseGunnerGear
  equipment:
    head: N14ClothingHeadHatChinese
    back: N14ClothingBackpackMilitaryFilled
    mask: N14ClothingMaskWhiteBalaclava
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryFilled2
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesLeather
    outerClothing: N14ClothingOuterVestChinese
    pocket2: N14CombatKnife
    suitstorage: N14WeaponLMGchinese

- type: playTimeTracker
  id: ChineseGunner
