- type: job
  id: ChineseOfficer
  setPreference: true
  name: "китайський офіцер"
  description: "очолити свої війська і битися в ім'я комунізму." #need work
  playTimeTracker: ChineseOfficer
  startingGear: ChineseOfficerGear
  icon: "JobIconSecurityCadet"

- type: startingGear
  id: ChineseOfficerGear
  equipment:
    head: N14ClothingHeadHatChinese
    back: N14ClothingBackpackMilitaryFilled
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryFilled
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesLeather
    outerClothing: N14ClothingOuterVestChinese
    pocket1: N14WeaponPistol9mmChinese
    pocket2: N14CombatKnife
    suitstorage: N14ChineseSword

- type: playTimeTracker
  id: ChineseOfficer
