- type: job
  id: ChineseSpecOps
  setPreference: true
  name: "китайські спецоперації"
  description: "виконувати накази начальства, боротися за комунізм." #need work
  playTimeTracker: ChineseSpecOps
  startingGear: ChineseSpecOpsGear
  icon: "JobIconSecurityCadet"

- type: startingGear
  id: ChineseSpecOpsGear
  equipment:
    head: N14ClothingHeadHatChineseHelmetMk2
    back: N14ClothingBackpackMilitaryFilled
    mask: N14ClothingMaskWhiteBalaclava
    belt: ClothingBeltMilitaryFilled5
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsCombatMK2
    gloves: N14ClothingHandsGlovesCombat
    outerClothing: N14ClothingOuterCombatArmorChinese
    pocket1: N14WeaponPistol9mmChinese
    pocket2: N14CombatKnife
    suitstorage: N14WeaponSMG12mmAdvancedChinese

- type: playTimeTracker
  id: ChineseSpecOps
