- type: entity
  parent: MobHuman
  id: N14MobHumanRanger
  name: "Пустельний рейнджер"
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitary
      - NamesLastMilitary
    - type: NpcFactionMember
      factions:
      - Rangers

- type: entity
  parent: MobHuman
  id: N14MobHumanRangerRecruit
  name: "Рекрут пустельного рейнджера"
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerRecruitGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitary
      - NamesLastMilitary
    - type: NpcFactionMember
      factions:
      - Rangers

- type: entity
  parent: MobHuman
  id: N14MobHumanRangerVeteran
  name: "Ветеран пустельних рейнджерів"
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerVeteranGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitaryLeader
      - NamesLastMilitary
    - type: NpcFactionMember
      factions:
      - Rangers

- type: entity
  parent: MobHuman
  id: N14MobHumanRangerChief
  name: "Шеф пустельних рейнджерів"
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerChiefGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitaryLeader
      - NamesLastMilitary
    - type: AutoImplant
      implants:
      - DeathAcidifierImplant
    - type: NpcFactionMember
      factions:
      - Rangers

#TODO add pictures for the entitylist
