- type: job
  id: Magistrate
  name: "Магістрат"
  description: "Забезпечувати дотримання Космічного Закону, Підтримувати Правосуддя та Законність, Проводити Слухання та Суди, Дотримуватися СОП, Забезпечувати дотримання Космічного Закону командуванням."
  playTimeTracker: JobMagistrate
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 54000 # 15 hours
    # - !type:CharacterTraitRequirement
      # inverted: true
      # traits:
        # - Foreigner
        # - ForeignerLight
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Detective
  - Corpsman
  - Command
  - CentralCommand
  - Magistrate
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh
  setPreference: false

- type: startingGear
  id: MagistrateGear
  subGear:
  - MagistratePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMagistrate
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorWhite
    id: CentcomPDA
    ears: ClothingHeadsetMagistrate
    pocket1: UniqueMagistrateLockerTeleporter

- type: startingGear
  id: MagistratePlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMagistrate
    head: ClothingHeadEnvirohelmMagistrate
    gloves: ClothingHandsGlovesEnviroglovesWhite
