- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: "посада-опис-каральний-загін"
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand