- type: entity
  id: CrateSecurityArmor
  parent: CrateSecgear
  name: "броньований ящик"
  description: "Три бронежилети, що добре захищають від ударів. Для відкриття потрібен доступ до служби безпеки."
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBulletproof replaced in favour of plate carrier
        amount: 3

- type: entity
  id: CrateSecurityHelmet
  parent: CrateSecgear
  name: "ящик для шолома"
  description: "Містить три стандартних відра для мозку. Для відкриття потрібен доступ від служби безпеки."
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
        amount: 3

- type: entity
  id: CrateSecurityNonlethal
  parent: CrateSecgear
  name: "нелетальний ящик"
  description: "Зброя з деактиватором. Для відкриття потрібен доступ до системи безпеки."
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisabler
        amount: 3
      - id: Stunbaton
        amount: 3
      - id: BoxFlashbang
      - id: Flash
        amount: 3
#      - Pepperspray
#      - GrenadeTeargas

- type: entity
  id: CrateSecurityRiot
  parent: CrateSecgear
  name: "ящик для валків"
  description: "Містить два комплекти бронежилетів, шоломи, щити та спецпризначенців, споряджених мішками з бобами. Додаткові боєприпаси включені. Для відкриття потрібен доступ до арсеналу."
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorARC # DeltaV - ClothingOuterArmorRiot replaced in favour of ARC suit
        amount: 2
      - id: ClothingHeadHelmetRiot
        amount: 2
      - id: WeaponShotgunEnforcerRubber
        amount: 2
      - id: BoxBeanbag
        amount: 2
      - id: RiotShield
        amount: 2
#      - SecGasmask

- type: entity
  id: CrateSecuritySupplies
  parent: CrateSecgear
  name: "ящик для засобів безпеки"
  description: "Містить різні припаси для служби безпеки станції. Для відкриття потрібен доступ служби безпеки."
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
      - id: BoxSechud
#      - SecBelt
#      - SecGasmask
#      - SpacelawBook

- type: entity
  id: CrateRestraints
  parent: CrateSecgear
  name: "обмежувальний ящик"
  description: "Містить по дві коробки з наручниками та застібками-блискавками. Для відкриття потрібен доступ служби безпеки."
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
        amount: 2
      - id: BoxZiptie
        amount: 2

- type: entity
  id: CrateSecurityBiosuit
  parent: CrateSecgear
  name: "захисний ящик для біокостюму"
  description: "Містить 2 костюми біозахисту, щоб жодна хвороба не відволікала вас від виконання ваших обов'язків. Для відкриття потрібен доступ до системи безпеки."
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterBioSecurity
        amount: 2
      - id: ClothingHeadHatHoodBioSecurity
        amount: 2
      - id: ClothingMaskSterile
        amount: 2

- type: entity
  id: CrateSecurityTrackingMindshieldImplants
  name: "ящик для імплантації"
  description: "Містить 4 імплантати MindShield та 4 імплантати для відстеження. Для відкриття потрібен доступ до системи безпеки."
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - id: MindShieldImplanter
        amount: 4
      - id: TrackingImplanter
        amount: 4

# Cosmetic Crates
