- type: job
  id: MountieCorporal
  setPreference: true
  name: "капрал гірської піхоти"
  description: "виконувати накази свого сержанта" #need work
  playTimeTracker: MountieCorporal
  startingGear: MountieCorporalGear
  icon: "JobIconSecurityCadet"

- type: startingGear
  id: MountieCorporalGear
  equipment:
    head: N14ClothingHeadHatMountie
    back: N14ClothingBackpackMilitaryMountieFilled
    belt: ClothingBeltMountieFilled
    jumpsuit: N14ClothingUniformJumpsuitRCMP
    shoes: N14ClothingBootsMountie
    gloves: N14ClothingHandsGlovesMountie
    outerClothing: N14ClothingOuterVestRCMP
    pocket1: N14WeaponRevolverWebley
    pocket2: N14CombatKnife
    suitstorage: N14WeaponSniperEnfield
  innerClothingSkirt: N14ClothingUniformJumpsuitRCMP #placeholder
  satchel: N14ClothingBackpackMilitaryMountieFilled

- type: playTimeTracker
  id: MountieCorporal
