- type: entity
  parent: MobHuman
  id: N14MobHumanRCMPSergeant
  name: "Сержант канадської конної поліції"
  components:
    - type: Icon
      sprite: _Nuclear14/Markers/Jobs/mounties.rsi
      state: sergeant
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [MountieSergeantGear]

- type: entity
  parent: N14MobHumanRCMPSergeant
  id: N14MobHumanRCMPCorporal
  name: "Капрал кавалерії КККП"
  components:
    - type: Icon
      state: corporal
    - type: Loadout
      prototypes: [MountieCorporalGear]

- type: entity
  parent: N14MobHumanRCMPSergeant
  id: N14MobHumanRCMPSkirmisher
  name: "Кавалерійський стрілець RCMP"
  components:
    - type: Icon
      state: skirmisher
    - type: Loadout
      prototypes: [MountieSkirmisherGear]
